### ISSUE TITLE
Possible to get a raw sample image ?

### ISSUE THREAD

**Issue by Leo-Mrl** [mgharbi/hdrnet_legacy#14]
The title says it all : could it please be possible to get a sample raw image from your set ? When I try your hdr+ model with mine (doing all the necessary pre-processing), I always obtain a viewable image, but with serious color imbalances.

Let me know if you need any other information.

**Comment by mgharbi** [comment]
This is a known issue, we used images from the HDR+ dataset: http://hdrplusdata.org/dataset.html. Unfortunately, the data format has changed since we trained the provided model and I haven't retrained it.
