### ISSUE TITLE
Cuda implementation

### ISSUE THREAD

**Issue by dragonkao730** [mgharbi/hdrnet_legacy#16]
Hi, Maghrebi

Your paper is wonderful, and thank you for providing the source code.
I have a little question about the Cuda implement part.
Have you tested the differences between using Cuda and not using Cuda?
Because 'Slice' is 'Bilinear Sample Op' and a lot of Tensorflow user implant it in python,
'Apply' part is 'Matmul Op', Tensorflow also has the Op.
I would like to ask how much performance improvement when using Cuda?

Thank you!

**Comment by mgharbi** [comment]
We'll have a report on that soon. From benchmarks I run, the CUDA implementation is 3-4x faster than tensorflow/pytorch. There's a way to implement it in Tensorflow, but not with the Bilinear Sample op. the Bilateral slice is a _trilinear_ interpolation. A TF implementation runs out of memory for 4Mpix images.
