### ISSUE TITLE
Fusion implementation

### ISSUE THREAD

**Issue by dragonkao730** [mgharbi/hdrnet_legacy#17]
Hi Mgharbi,

I have a small question about Fusion.
In paper, Fusion part looks like a 1x1 Conv,
but models.py#L125 just add 2 tensors together.
`fusion = tf.nn.relu(fusion_grid+fusion_global)`

Thanks!

**Comment by mgharbi** [comment]
w1*fusion_grid + w2*fusion_global

is equivalent to w3*(w1*fusion_grid + w2*fusion_global) by linearity. Assuming w3 is the a 1x1 kernel, you just fold in the weights in the previous layers, there’s no activation before that.

**Comment by dragonkao730** [comment]
I understand! Thank you for your reply!
