### ISSUE TITLE
Cannot build with TF1.8 and CUDA9.0

### ISSUE THREAD

**Issue by cchen156** [mgharbi/hdrnet_legacy#24]
After I upgrade the tensorflow to 1.8.0, there is some error for ''py.test test". The main difference seems that we need to link the tensorflow_framework.so in the makefile. 

After this change, I still get an error: 

lib_handle = py_tf.TF_LoadLibrary(library_filename)
E   NotFoundError: ***/hdrnet/hdrnet/lib/hdrnet_ops.so: undefined symbol: _Z37BilateralSliceApplyGradKernelLauncherRKN5Eigen9GpuDeviceEPKfPKxS4_S6_S4_S6_S4_bPfS7_S7_

I have no idea what I need to change in the makefile. 

Thanks!

**Comment by wzl2611** [comment]
following is my makefile. hope that can help you. maybe you can downgrade you tensorflow to 1.1.0

TF_INC ?= `python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())'`
# TF_INC ?= /usr/local/lib/python2.7/dist-packages/tensorflow/include
CUDA_HOME ?= /usr/local/cuda

SRC_DIR = ops

BUILD_DIR = build
LIB_DIR = lib

CC = c++ -std=c++11
NVCC = nvcc -std c++11
CFLAGS = -fPIC -I$(TF_INC) -O2 -D_GLIBCXX_USE_CXX11_ABI=0
LDFLAGS = -L$(CUDA_HOME)/lib64 -lcudart
NVFLAGS = -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -I$(TF_INC) -I$(SRC_DIR)\
					-gencode=arch=compute_30,code=\"sm_30,compute_30\" \
					-expt-relaxed-constexpr -Wno-deprecated-gpu-targets -ftz=true --ptxas-options=-v -lineinfo


SRC = bilateral_slice.cc
CUDA_SRC = bilateral_slice.cu.cc
CUDA_OBJ = $(addprefix $(BUILD_DIR)/,$(CUDA_SRC:.cc=.o))
SRCS = $(addprefix $(SRC_DIR)/, $(SRC))

all: $(LIB_DIR)/hdrnet_ops.so

# Main library
$(LIB_DIR)/hdrnet_ops.so: $(CUDA_OBJ) $(LIB_DIR) $(SRCS)
	$(CC) -shared -o $@ $(SRCS) $(CUDA_OBJ) $(CFLAGS) $(LDFLAGS) 

# Cuda kernels
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cc $(BUILD_DIR)
	$(NVCC) -c  $< -o $@ $(NVFLAGS)

$(BUILD_DIR):
	mkdir -p $@


$(LIB_DIR):
	mkdir -p $@

clean:
	rm -rf $(BUILD_DIR) $(LIB_DIR)

**Comment by cchen156** [comment]
I still got the error after I change tensorflow to 1.1 and g++ to 4.9.

**Comment by cchen156** [comment]
Finally make it work with TF1.1 + CUDA8.0 + g++ 4.9
