### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by FatimaNiazi01** [mgharbi/hdrnet_legacy#26]
Thanks. Can you please tell the the files namely android/assets/camera_preview.frag
android/jni/convert_image_hl.cxx
android/jni/convert_output_hl.cxx
Where these can be found?
These are mentioned in readme file in Android portion.

**Comment by butterl** [comment]
@FatimaNiazi01  where did you get the Android code？ seems not release from this repo

**Comment by mgharbi** [comment]
these are not released.
