### ISSUE TITLE
Preparing data for experts models

### ISSUE THREAD

**Issue by vikasrs** [mgharbi/hdrnet_legacy#32]
Dear Gharbi,

Can you please shed some light on how you prepared Adobe-MIT5K dataset to train the expert models? What operations were performed to convert the raw format .DNG files to RGB? 

More specifically, was white balance and gamma corrections applied to raw input?

Thanks

**Comment by mgharbi** [comment]
The MIT5k dataset comes with an Adobe Lightroom catalog file. This file contains all the setting needed to produce the input/output images.

Specifically, for each ‘expert’, eg expertA we selected the corresponding rendition/preset in the Lightroom catalog then exported the image to .jpg : this is the output of the ‘filter’ we want to learn. For the input, we used the ‘unprocessed’ preset.

Mika

**Comment by vikasrs** [comment]
Thanks for the info.
