### ISSUE TITLE
How do I use the .bin file on the Android platform to generate the "guidance map" in Section 3.4.1 of the paper?

### ISSUE THREAD

**Issue by TCBocean** [mgharbi/hdrnet_legacy#42]
Your work is great. Now I trained my model, but I encountered some problems during deployment.

I saw in the README file that on the Android platform you need to run freeze_graph.py to freeze the model. There is a series of .bin files generated, I guess this is used to calculate the "guidance map". But I am not quite sure how to apply it on the Android side. How should they be loaded and calculate the "guidance map" result.

I hope you can help me, thank you.

**Comment by ColdCodeCool** [comment]
Hi, do you manage to build your android demo?

**Comment by TCBocean** [comment]
@ColdCodeCool 
Yes, I have made an Android demo, but I did not use OpenGL, but only used C ++ for rendering. The 4k image takes about two seconds on the Snapdragon 660 mobile phone. I don't know how to use OpenGL, so I didn't implement OpenGL to do the rendering work.
