### ISSUE TITLE
Question about your reported 'experts' result

### ISSUE THREAD

**Issue by rockeyben** [mgharbi/hdrnet_legacy#44]
It's just about Lab space error.

I run the 'experts C' experiment according to your scripts, with a 4500-500 train-test split. I trained about 100k step, the eval PSNR came round 22.5. Then I use cv2.cvtColor(BGR2Lab) to convert BGR to Lab space and calculate l2 error. According to [opencv document](https://docs.opencv.org/2.4/modules/imgproc/doc/miscellaneous_transformations.html#cvtcolor), the output Lab range is in [0, 255], but actually we need to scale 'L' channel into [0, 100]. Meanwhile, 'a' channel and 'b' channel shouldn't be scaled, instead just add an bias of 128.

Then something interesting happened. My original result in Lab(range[0, 255]) is around 52, if I scale 'L' channel only, the result will decrease to around 40, which is much higher than your reported '7.8'
![image](https://user-images.githubusercontent.com/27840904/62757265-57ffc800-baad-11e9-9580-d72f39cac51b.png)
But if I scale all the channels, including 'a' and 'b' channel, the result comes to 7.9, which seems more consistent with your paper results.
So I am wondering whether you scaled all the channels and report this result.

Thanks.

**Comment by mgharbi** [comment]
As far as I recall, we followed the experimental procedure of previous work for this comparison with L*a*b* values in [0,100]x[-127, 127]^2. We did not use the OpenCV implementation of the RGB2Lab tranform.

In particular:
https://arxiv.org/pdf/1412.7725.pdf
https://www.microsoft.com/en-us/research/wp-content/uploads/2012/10/eccv2012_final.pdf

Hope this helps!
