### ISSUE TITLE
Is it possible to release the camera_preview.frag?

### ISSUE THREAD

**Issue by ColdCodeCool** [mgharbi/hdrnet_legacy#50]
Hi, Michael.
     I was wondering if you can release the camera_preview.frag in the android demo part. I am trying to build a real-time hdrnet demo. It would be great helpful that you could share the code. Thank you!

**Comment by mgharbi** [comment]
Hi, I unfortunately cannot release this piece of the code. But the algorithm is this one: 
https://github.com/mgharbi/hdrnet_legacy/blob/b06d0119e2fb22c62c757161e6d351a304720544/hdrnet/ops/bilateral_slice.cu.cc#L224
