### ISSUE TITLE
Weight restore problem for custom image shape

### ISSUE THREAD

**Issue by sumsuddin** [mgharbi/hdrnet_legacy#6]
I have trained some 32 * 32 images (same input and output shape) using following command.

> python train.py /Models/hdrnet/ /Data/filelist.txt --net_input_size 32 --output_resolution 32 32

The training was completed with no problem.
Now, when I run the `run.py` using the following command

> python run.py /Models/hdrnet/ /Data/set/input/ /Data/set/gen/

I get some error like below

> tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1024,256] rhs shape= [65536,256]

I think some layers are not loading the dimensions correctly in `run.py` from the saved model.

Please help me to resolve the problem.

**Edit** Now that I have found the source of the issue. It is on [this](https://github.com/mgharbi/hdrnet/blob/e2f1833e0afe9781eaed942d4c9bb6db496f4bc0/hdrnet/data_pipeline.py#L166) line of `data_pipeline.py` file. This will create a problem for any training set other than 256 image size.

**Comment by mgharbi** [comment]
You're welcome to submit a pull request to fix this bug. Thanks for finding it!
