### ISSUE TITLE
No module named hdrnet.metrics !!!

### ISSUE THREAD

**Issue by Hosseinhashemiir** [mgharbi/hdrnet_legacy#8]
I will be pleased if you help me.
 after I'm using this command I will get the error :
python train.py /pretrained_models/  /sample_data/identity/input/ /sample_data/identity/filelist.txt

Traceback (most recent call last):
  File "train.py", line 26, in <module>
    import hdrnet.metrics as metrics
ImportError: No module named hdrnet.metrics

**Comment by kubytskyi** [comment]
Try running the same from the directory above.

**Comment by mgharbi** [comment]
Yes, essentially the module hdrnet should be in your PYTHONPATH. If, for example, you use virtualenv the current working directory is automatically added to this variable. And running the command from the root directory of the python package should work: ./bin/train.py
