### ISSUE TITLE
make benchmark / tensorflow/core/public/session.h: No such file

### ISSUE THREAD

**Issue by stanfordism** [mgharbi/hdrnet_legacy#9]
I get some error when I use the command to make for the benchmark.
is there any suggestion? thanks.

`mkdir -p bin
c++ -std=c++11 -O2 -o bin/benchmark src/main.cc src/renderer.cc src/utils.cc src/processor.cc -fPIC -I `pkg-config opencv --cflags` -Iinclude `pkg-config opencv --libs` -L -ltensorflow -lglut -lGLEW -lGL -lgflags 
In file included from src/main.cc:28:0:
include/processor.h:21:44: fatal error: tensorflow/core/public/session.h: No such file or directory
compilation terminated.
In file included from src/processor.cc:15:0:
include/processor.h:21:44: fatal error: tensorflow/core/public/session.h: No such file or directory
compilation terminated.
Makefile:20: recipe for target 'bin/benchmark' failed
make: *** [bin/benchmark] Error 1`

**Comment by Rachnog** [comment]
Try to add
```
TF_INC ?= `python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())'`
```
to the Makefile for benchmark

**Comment by ho-suk-93** [comment]
The reason of this problem is that the path of tensorflow changed in current version.
To solve this problem, add a line below to your Makefile.
`CFLAGS += -I/usr/local/lib/python2.7/dist-packages/tensorflow/include`
